version: '3.8'
services:
  kalamar:
    image: "korap/kalamar:latest-conv"
    ports:
      - "64543:64543"
    environment:
      KALAMAR_API: "http://kustvakt:8089/api/"
    depends_on:
      - kustvakt
    profiles:
      - lite
    restart: "unless-stopped"
  full-init:
    image: "korap/kalamar:latest-conv"
    command: super_client_info kalamar /kalamar/data/super_client_info
    volumes:
      - type: bind
        source: "${PWD}/data/"
        target: "/kalamar/data"
    profiles:
      - full
      - init
    user: root
    restart: "no"
  kalamar-full:
    image: "korap/kalamar:latest-conv"
    ports:
      - "64543:64543"
    environment:
      KALAMAR_API: "http://kustvakt-full:8089/api/"
    volumes:
      - type: bind
        source: "${PWD}/data/kalamar.production.conf"
        target: "/kalamar/kalamar.production.conf"
      - type: bind
        source: "${PWD}/data/super_client_info"
        target: /kalamar/super_client_info
    depends_on:
      kustvakt-full:
        condition: service_started
      full-init:
        condition: service_completed_successfully
    profiles:
      - full
    restart: "unless-stopped"
    user: root
  kustvakt:
    image: "korap/kustvakt:latest"
    expose:
      - 8089
    volumes:
      - "${INDEX}:/kustvakt/index:z"
    profiles:
      - lite
    restart: "unless-stopped"
  kustvakt-full:
    image: "korap/kustvakt:latest-full"
    expose:
      - 8089
    user: root
    volumes:
      - "${INDEX}:/kustvakt/index:z"
      - type: bind
        source: "${PWD}/data/"
        target: /kustvakt/data/
    profiles:
      - full
    depends_on:
      full-init:
        condition: service_completed_successfully
    restart: "unless-stopped"
configs:
  super_client_info:
    external: true
